/*
 * Copyright (c) 2012 by Fernando Correa da Conceição
 *
 * This is released under MIT license, read the file LICENSE.txt or
 * http://opensource.org/licenses/mit-license.php .
 *
 * IMPORTANT: some parts of this file are generated by the form builder in
 * netbeans, this is the reason of some diferences in code style.
 */
package br.net.jaguaribe.jaguaribe;

/**
 * Frame to add a new bookmark.
 *
 * This class create a frame and implements the task to add a new bookmark.
 *
 * @author Fernando Correa da Conceição.
 */
public class BookmarksAddFrame extends javax.swing.JDialog {

    /**
     * Used in class serialization.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Store the Main Frame(JaguaribeFrame).
     */
    private JaguaribeFrame parent;

    /**
     * Creates new form BookmarksAddFrame
     *
     * @param parent The parent frame, we need this for modal frame.
     * @param modal If the frame is modal.
     */
    public BookmarksAddFrame(JaguaribeFrame parent, boolean modal) {
        super(parent, modal);
        this.parent = parent;
        initComponents();

        this.buttonChooseFile.setTextField(this.textPath);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitle = new javax.swing.JLabel();
        textTitle = new javax.swing.JTextField();
        textPath = new javax.swing.JTextField();
        labelPath = new javax.swing.JLabel();
        buttonOk = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        labelDialogTitle = new javax.swing.JLabel();
        buttonChooseFile = new br.net.jaguaribe.common.ButtonChooseFile();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setModal(true);
        setName("dialog"); // NOI18N

        labelTitle.setText("Title");
        labelTitle.setName("title"); // NOI18N

        labelPath.setText("Path");

        buttonOk.setText("Ok");
        buttonOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonOkMouseClicked(evt);
            }
        });

        buttonCancel.setText("Cancel");
        buttonCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCancelMouseClicked(evt);
            }
        });

        labelDialogTitle.setText("Add Bookmark");

        buttonChooseFile.setText(". . .");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(labelDialogTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelPath))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textPath, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(textTitle))))
                        .addGap(18, 18, 18)
                        .addComponent(buttonChooseFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelDialogTitle)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTitle)
                    .addComponent(textTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPath)
                    .addComponent(buttonChooseFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(buttonCancel)
                    .addComponent(buttonOk)))
        );

        labelTitle.getAccessibleContext().setAccessibleName("title");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * When the button ok is clicked.
     *
     * @param evt The event.
     */
    private void buttonOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonOkMouseClicked
        BookmarksItem item = new BookmarksItem();
        item.setName(this.textTitle.getText());
        item.setPath(this.textPath.getText());
        BookmarksData data = BookmarksData.getInstance();
        Boolean answer = data.add(item);
        if (answer) {
            Jaguaribe.getInstance().getFrame().addBookmark(item);
        }
        this.dispose();
    }//GEN-LAST:event_buttonOkMouseClicked

    /**
     * When the button calcel is clicked.
     *
     * @param evt The event.
     */
    private void buttonCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCancelMouseClicked
        this.dispose();

    }//GEN-LAST:event_buttonCancelMouseClicked
    //@cond
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private br.net.jaguaribe.common.ButtonChooseFile buttonChooseFile;
    private javax.swing.JButton buttonOk;
    private javax.swing.JLabel labelDialogTitle;
    private javax.swing.JLabel labelPath;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JTextField textPath;
    private javax.swing.JTextField textTitle;
    // End of variables declaration//GEN-END:variables
    //@endcond
}
