/*
 * Copyright (c) 2012 by Fernando Correa da Conceição
 *
 * This is released under MIT license, read the file LICENSE.txt or
 * http://opensource.org/licenses/mit-license.php .
 */
package br.net.jaguaribe.about;

import br.net.jaguaribe.common.FileUtils;
import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;

/**
 * Create a dialog to show information about the application.
 *
 * @author Fernando Correa da Conceição.
 */
public class AboutDialog extends javax.swing.JDialog {

    /**
     * Id used for serialization.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Creates a new form AboutDialog.
     *
     * @param parent The parent frame.
     * @param modal True if want this dialog as modal.
     */
    public AboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * Creates a new form AboutDialog.
     *
     * @param parent The parent frame.
     * @param title The title of dialog.
     */
    public AboutDialog(JFrame parent, String title) {
        super(parent, title);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Add a new tab to dialog.
     *
     * @param title The title of table
     * @param file The name of the file with the content to show in the tab. The
     * file must be on jar file.
     */
    public void addTab(String title, String file) {
        this.addTabText(title, FileUtils.readFromJarFile(file));
    }

    /**
     * Add a new tab in the window.
     *
     * @param title The title of the tab.
     * @param content The content of the tab(can be HTML).
     */
    public void addTabText(String title, String content) {
        JPanel panel = new JPanel();
        panel.setLayout(new BorderLayout());
        JTextPane tab = new JTextPane();
        JScrollPane scroll = new JScrollPane(tab);
        scroll.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        tab.setEditable(false);
        tab.setText(content);
        panel.add(scroll, BorderLayout.CENTER);
        this.tabbedPane.add(title, panel);
    }
    //@cond
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
    //@endcond
}
